# docker-compose.yml
version: '3.8'

networks:
  calcount_net:
    driver: bridge

services:

  redis:
    image: "redis:7.2-alpine"
    command: redis-server --requirepass "test123"
    expose:
     - "6379"
    ports:
      - 6379:6379
    networks:
      - calcount_net

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: calcount123
      POSTGRES_DB: calcount
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - calcount_net

  fastapi:
    image: calcount-fastapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    networks:
      - calcount_net

volumes:
  postgres_data: